# Generated by Django 4.2 on 2023-09-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ImageField(null=True, upload_to='photos/products'),
        ),
    ]
