# Generated by Django 4.2 on 2023-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_price',
            field=models.IntegerField(blank=True),
        ),
    ]
