# Generated by Django 4.2.5 on 2023-10-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="wallet",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
