# Generated by Django 4.2.5 on 2023-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authenticator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="DOB",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
