# Generated by Django 4.2 on 2023-09-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_account_otp_account_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='account',
            name='otp_expiry',
        ),
    ]
