# Generated by Django 4.2.5 on 2023-09-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_remove_account_otp_remove_account_otp_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_superadmin',
            new_name='is_superuser',
        ),
    ]
