# Generated by Django 4.2.5 on 2023-10-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_cart", "0003_alter_coupon_discount_alter_coupon_minimum_amount"),
        ("user_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_cart.coupon",
            ),
        ),
    ]
