# Generated by Django 4.2.5 on 2023-10-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_panel", "0003_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="subtotal",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
