# Generated by Django 4.2 on 2023-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0004_cart_item_is_active_cart_item_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True),
        ),
    ]
