# Generated by Django 4.2.5 on 2023-09-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_remove_cart_session_id_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
