# Generated by Django 4.2.5 on 2023-10-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0007_remove_cart_cart_id_remove_cart_item_user_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
