# Generated by Django 4.2.5 on 2023-10-16 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="wallet",
        ),
    ]
