# Generated by Django 4.2.5 on 2023-10-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_cart", "0003_alter_coupon_discount_alter_coupon_minimum_amount"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="additional_discount",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_cart.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="wallet_discount",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
