# Generated by Django 4.2.5 on 2023-10-15 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_additional_discount_order_coupon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
    ]
